name: Flask CI/CD

on:
  push:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12.4

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging info
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory" $(pwd)
          echo "Contents of Working Directory: $(ls-l)"
          echo "Contents of site-packages: $(ls-1 venv/lib/python*/site-packages)"


  test:
    needs: build
    runs on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.12.4

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run tests
        run: pythn -m unittest discover -s tests -p "test_*.py"